/**
 * dev server
 * SwissHomeGuard mocked API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ch.swisshomeguard.model.dummy

/**
 *
 * @param camera_id
 * @param stream_url
 * @param preview_url
 * @param detection_zones
 * @param suppression_zones
 * @param detecting
 * @param active_alarm
 * @param size_filter
 * @param detection_model_name
 * @param detection_device_name
 * @param fps
 */
data class DummyCamera(
    val camera_id: java.util.UUID,
    val stream_url: String,
    val preview_url: String? = null,
    val detection_zones: Array<Zone>? = null,
    val suppression_zones: Array<Zone>? = null,
    val detecting: Boolean? = null,
    val active_alarm: Boolean? = null,
    val size_filter: SizeFilter? = null,
    val detection_model_name: String? = null,
    val detection_device_name: String? = null,
    val fps: Int? = null
)

