/**
 * dev server
 * SwissHomeGuard mocked API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ch.swisshomeguard.model.dummy

/**
 *
 * @param id
 * @param event_id
 * @param creation_date
 * @param camera_id
 * @param recordings
 * @param status event processing status
 */
data class DummyEvent(
    val creation_date: java.time.LocalDateTime,
    val id: kotlin.Long? = null,
    val event_id: kotlin.Long? = null,
    val camera_id: java.util.UUID? = null,
    val recordings: kotlin.Array<DummyRecording>? = null,
)

