/**
 * dev server
 * SwissHomeGuard mocked API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ch.swisshomeguard.model.dummy

/**
 *
 * @param x
 * @param y
 */
data class PolygonPoint(
    val x: Int,
    val y: Int
)

