/**
 * dev server
 * SwissHomeGuard mocked API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ch.swisshomeguard.model.dummy

/**
 *
 * @param min_width
 * @param max_width
 * @param min_height
 * @param max_height
 */
data class SizeFilter(
    val min_width: Int? = null,
    val max_width: Int? = null,
    val min_height: Int? = null,
    val max_height: Int? = null
)

